
// This file has been generated by the GUI designer. Do not modify.
namespace OPDtabGui
{
	public partial class RoundResultSetBest
	{
		private global::Gtk.HBox hbox;

		private global::Gtk.Image image;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget OPDtabGui.RoundResultSetBest
			global::Stetic.BinContainer.Attach (this);
			this.Name = "OPDtabGui.RoundResultSetBest";
			// Container child OPDtabGui.RoundResultSetBest.Gtk.Container+ContainerChild
			this.hbox = new global::Gtk.HBox ();
			this.hbox.Name = "hbox";
			// Container child hbox.Gtk.Box+BoxChild
			this.image = new global::Gtk.Image ();
			this.image.Name = "image";
			this.image.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("OPDtabGui.Icons.go-previous.png");
			this.hbox.Add (this.image);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox [this.image]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.Add (this.hbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
