
// This file has been generated by the GUI designer. Do not modify.
namespace OPDtabGui
{
	public partial class DebaterPool
	{
		private global::Gtk.Notebook notebookDragDrop;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.VBox vbox1;

		private global::Gtk.VBox vboxTeams;

		private global::Gtk.Label label1;

		private global::Gtk.Label labelTeamList;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.VBox vboxJudges;

		private global::Gtk.Label label2;

		private global::Gtk.Label labelJudgeList;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget OPDtabGui.DebaterPool
			global::Stetic.BinContainer.Attach(this);
			this.Name = "OPDtabGui.DebaterPool";
			// Container child OPDtabGui.DebaterPool.Gtk.Container+ContainerChild
			this.notebookDragDrop = new global::Gtk.Notebook();
			this.notebookDragDrop.WidthRequest = 200;
			this.notebookDragDrop.CanFocus = true;
			this.notebookDragDrop.Name = "notebookDragDrop";
			this.notebookDragDrop.CurrentPage = 0;
			this.notebookDragDrop.ShowBorder = false;
			// Container child notebookDragDrop.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			// Container child vbox1.Gtk.Box+BoxChild
			this.vboxTeams = new global::Gtk.VBox();
			this.vboxTeams.Name = "vboxTeams";
			this.vbox1.Add(this.vboxTeams);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vboxTeams]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.vbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
			w3.Position = 1;
			w1.Add(this.vbox1);
			this.GtkScrolledWindow.Add(w1);
			this.notebookDragDrop.Add(this.GtkScrolledWindow);
			// Notebook tab
			this.labelTeamList = new global::Gtk.Label();
			this.labelTeamList.Name = "labelTeamList";
			this.labelTeamList.LabelProp = "<b>Teams</b> (0)";
			this.labelTeamList.UseMarkup = true;
			this.notebookDragDrop.SetTabLabel(this.GtkScrolledWindow, this.labelTeamList);
			this.labelTeamList.ShowAll();
			// Container child notebookDragDrop.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w7 = new global::Gtk.Viewport();
			w7.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport1.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			// Container child vbox2.Gtk.Box+BoxChild
			this.vboxJudges = new global::Gtk.VBox();
			this.vboxJudges.Name = "vboxJudges";
			this.vbox2.Add(this.vboxJudges);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vboxJudges]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.vbox2.Add(this.label2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label2]));
			w9.Position = 1;
			w7.Add(this.vbox2);
			this.GtkScrolledWindow1.Add(w7);
			this.notebookDragDrop.Add(this.GtkScrolledWindow1);
			global::Gtk.Notebook.NotebookChild w12 = ((global::Gtk.Notebook.NotebookChild)(this.notebookDragDrop[this.GtkScrolledWindow1]));
			w12.Position = 1;
			// Notebook tab
			this.labelJudgeList = new global::Gtk.Label();
			this.labelJudgeList.Name = "labelJudgeList";
			this.labelJudgeList.LabelProp = "<b>Judges</b> (0)\n<small><small>1/J/C/X=0/0/0/0</small></small>";
			this.labelJudgeList.UseMarkup = true;
			this.notebookDragDrop.SetTabLabel(this.GtkScrolledWindow1, this.labelJudgeList);
			this.labelJudgeList.ShowAll();
			this.Add(this.notebookDragDrop);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.notebookDragDrop.SwitchPage += new global::Gtk.SwitchPageHandler(this.OnNotebookDragDropSwitchPage);
		}
	}
}
