
// This file has been generated by the GUI designer. Do not modify.
namespace OPDtabGui
{
	public partial class RoundResultSheet
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Table table;
		private global::Gtk.EventBox ebFree1;
		private global::Gtk.Frame frame7;
		private global::Gtk.Alignment cFree1;
		private global::Gtk.Label GtkLabel6;
		private global::Gtk.EventBox ebFree2;
		private global::Gtk.Frame frame8;
		private global::Gtk.Alignment cFree2;
		private global::Gtk.Label GtkLabel7;
		private global::Gtk.EventBox ebFree3;
		private global::Gtk.Frame frame9;
		private global::Gtk.Alignment cFree3;
		private global::Gtk.Label GtkLabel8;
		private global::Gtk.EventBox ebGov1;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment cGov1;
		private global::Gtk.Label lblGov1;
		private global::Gtk.EventBox ebGov2;
		private global::Gtk.Frame frame3;
		private global::Gtk.Alignment cGov2;
		private global::Gtk.Label lblGov2;
		private global::Gtk.EventBox ebGov3;
		private global::Gtk.Frame frame11;
		private global::Gtk.Alignment cGov3;
		private global::Gtk.Label lblGov3;
		private global::Gtk.EventBox ebOpp1;
		private global::Gtk.Frame frame2;
		private global::Gtk.Alignment cOpp1;
		private global::Gtk.Label lblOpp1;
		private global::Gtk.EventBox ebOpp2;
		private global::Gtk.Frame frame6;
		private global::Gtk.Alignment cOpp2;
		private global::Gtk.Label lblOpp2;
		private global::Gtk.EventBox ebOpp3;
		private global::Gtk.Frame frame10;
		private global::Gtk.Alignment cOpp3;
		private global::Gtk.Label lblOpp3;
		private global::Gtk.EventBox ebTeamGov;
		private global::Gtk.Frame frame12;
		private global::Gtk.Alignment cTeamGov;
		private global::Gtk.Label GtkLabel11;
		private global::Gtk.EventBox ebTeamOpp;
		private global::Gtk.Frame frame13;
		private global::Gtk.Alignment cTeamOpp;
		private global::Gtk.Label GtkLabel12;
		private global::Gtk.Label label4;
		private global::Gtk.Label label5;
		private global::Gtk.Label lblNoRoomData;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget OPDtabGui.RoundResultSheet
			global::Stetic.BinContainer.Attach (this);
			this.Name = "OPDtabGui.RoundResultSheet";
			// Container child OPDtabGui.RoundResultSheet.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table = new global::Gtk.Table (((uint)(18)), ((uint)(1)), false);
			this.table.Name = "table";
			// Container child table.Gtk.Table+TableChild
			this.ebFree1 = new global::Gtk.EventBox ();
			this.ebFree1.Name = "ebFree1";
			// Container child ebFree1.Gtk.Container+ContainerChild
			this.frame7 = new global::Gtk.Frame ();
			this.frame7.Name = "frame7";
			this.frame7.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame7.Gtk.Container+ContainerChild
			this.cFree1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.cFree1.Name = "cFree1";
			this.cFree1.LeftPadding = ((uint)(12));
			this.frame7.Add (this.cFree1);
			this.GtkLabel6 = new global::Gtk.Label ();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>1. Free</i>");
			this.GtkLabel6.UseMarkup = true;
			this.frame7.LabelWidget = this.GtkLabel6;
			this.ebFree1.Add (this.frame7);
			this.table.Add (this.ebFree1);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table [this.ebFree1]));
			w3.TopAttach = ((uint)(7));
			w3.BottomAttach = ((uint)(8));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table.Gtk.Table+TableChild
			this.ebFree2 = new global::Gtk.EventBox ();
			this.ebFree2.Name = "ebFree2";
			// Container child ebFree2.Gtk.Container+ContainerChild
			this.frame8 = new global::Gtk.Frame ();
			this.frame8.Name = "frame8";
			this.frame8.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame8.Gtk.Container+ContainerChild
			this.cFree2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.cFree2.Name = "cFree2";
			this.cFree2.LeftPadding = ((uint)(12));
			this.frame8.Add (this.cFree2);
			this.GtkLabel7 = new global::Gtk.Label ();
			this.GtkLabel7.Name = "GtkLabel7";
			this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>2. Free</i>");
			this.GtkLabel7.UseMarkup = true;
			this.frame8.LabelWidget = this.GtkLabel7;
			this.ebFree2.Add (this.frame8);
			this.table.Add (this.ebFree2);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table [this.ebFree2]));
			w6.TopAttach = ((uint)(8));
			w6.BottomAttach = ((uint)(9));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table.Gtk.Table+TableChild
			this.ebFree3 = new global::Gtk.EventBox ();
			this.ebFree3.Name = "ebFree3";
			// Container child ebFree3.Gtk.Container+ContainerChild
			this.frame9 = new global::Gtk.Frame ();
			this.frame9.Name = "frame9";
			this.frame9.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame9.Gtk.Container+ContainerChild
			this.cFree3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.cFree3.Name = "cFree3";
			this.cFree3.LeftPadding = ((uint)(12));
			this.frame9.Add (this.cFree3);
			this.GtkLabel8 = new global::Gtk.Label ();
			this.GtkLabel8.Name = "GtkLabel8";
			this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>3. Free</i>");
			this.GtkLabel8.UseMarkup = true;
			this.frame9.LabelWidget = this.GtkLabel8;
			this.ebFree3.Add (this.frame9);
			this.table.Add (this.ebFree3);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table [this.ebFree3]));
			w9.TopAttach = ((uint)(9));
			w9.BottomAttach = ((uint)(10));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table.Gtk.Table+TableChild
			this.ebGov1 = new global::Gtk.EventBox ();
			this.ebGov1.Name = "ebGov1";
			// Container child ebGov1.Gtk.Container+ContainerChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.cGov1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.cGov1.Name = "cGov1";
			this.cGov1.LeftPadding = ((uint)(12));
			this.frame1.Add (this.cGov1);
			this.lblGov1 = new global::Gtk.Label ();
			this.lblGov1.Name = "lblGov1";
			this.lblGov1.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>1. Gov</i>");
			this.lblGov1.UseMarkup = true;
			this.frame1.LabelWidget = this.lblGov1;
			this.ebGov1.Add (this.frame1);
			this.table.Add (this.ebGov1);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table [this.ebGov1]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table.Gtk.Table+TableChild
			this.ebGov2 = new global::Gtk.EventBox ();
			this.ebGov2.Name = "ebGov2";
			// Container child ebGov2.Gtk.Container+ContainerChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.cGov2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.cGov2.Name = "cGov2";
			this.cGov2.LeftPadding = ((uint)(12));
			this.frame3.Add (this.cGov2);
			this.lblGov2 = new global::Gtk.Label ();
			this.lblGov2.Name = "lblGov2";
			this.lblGov2.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>2. Gov</i>");
			this.lblGov2.UseMarkup = true;
			this.frame3.LabelWidget = this.lblGov2;
			this.ebGov2.Add (this.frame3);
			this.table.Add (this.ebGov2);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table [this.ebGov2]));
			w15.TopAttach = ((uint)(4));
			w15.BottomAttach = ((uint)(5));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table.Gtk.Table+TableChild
			this.ebGov3 = new global::Gtk.EventBox ();
			this.ebGov3.Name = "ebGov3";
			// Container child ebGov3.Gtk.Container+ContainerChild
			this.frame11 = new global::Gtk.Frame ();
			this.frame11.Name = "frame11";
			this.frame11.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame11.Gtk.Container+ContainerChild
			this.cGov3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.cGov3.Name = "cGov3";
			this.cGov3.LeftPadding = ((uint)(12));
			this.frame11.Add (this.cGov3);
			this.lblGov3 = new global::Gtk.Label ();
			this.lblGov3.Name = "lblGov3";
			this.lblGov3.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>3. Gov</i>");
			this.lblGov3.UseMarkup = true;
			this.frame11.LabelWidget = this.lblGov3;
			this.ebGov3.Add (this.frame11);
			this.table.Add (this.ebGov3);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table [this.ebGov3]));
			w18.TopAttach = ((uint)(12));
			w18.BottomAttach = ((uint)(13));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table.Gtk.Table+TableChild
			this.ebOpp1 = new global::Gtk.EventBox ();
			this.ebOpp1.Name = "ebOpp1";
			// Container child ebOpp1.Gtk.Container+ContainerChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.cOpp1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.cOpp1.Name = "cOpp1";
			this.cOpp1.LeftPadding = ((uint)(12));
			this.frame2.Add (this.cOpp1);
			this.lblOpp1 = new global::Gtk.Label ();
			this.lblOpp1.Name = "lblOpp1";
			this.lblOpp1.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>1. Opp</i>");
			this.lblOpp1.UseMarkup = true;
			this.frame2.LabelWidget = this.lblOpp1;
			this.ebOpp1.Add (this.frame2);
			this.table.Add (this.ebOpp1);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table [this.ebOpp1]));
			w21.TopAttach = ((uint)(3));
			w21.BottomAttach = ((uint)(4));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table.Gtk.Table+TableChild
			this.ebOpp2 = new global::Gtk.EventBox ();
			this.ebOpp2.Name = "ebOpp2";
			// Container child ebOpp2.Gtk.Container+ContainerChild
			this.frame6 = new global::Gtk.Frame ();
			this.frame6.Name = "frame6";
			this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame6.Gtk.Container+ContainerChild
			this.cOpp2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.cOpp2.Name = "cOpp2";
			this.cOpp2.LeftPadding = ((uint)(12));
			this.frame6.Add (this.cOpp2);
			this.lblOpp2 = new global::Gtk.Label ();
			this.lblOpp2.Name = "lblOpp2";
			this.lblOpp2.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>2. Opp</i>");
			this.lblOpp2.UseMarkup = true;
			this.frame6.LabelWidget = this.lblOpp2;
			this.ebOpp2.Add (this.frame6);
			this.table.Add (this.ebOpp2);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table [this.ebOpp2]));
			w24.TopAttach = ((uint)(5));
			w24.BottomAttach = ((uint)(6));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table.Gtk.Table+TableChild
			this.ebOpp3 = new global::Gtk.EventBox ();
			this.ebOpp3.Name = "ebOpp3";
			// Container child ebOpp3.Gtk.Container+ContainerChild
			this.frame10 = new global::Gtk.Frame ();
			this.frame10.Name = "frame10";
			this.frame10.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame10.Gtk.Container+ContainerChild
			this.cOpp3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.cOpp3.Name = "cOpp3";
			this.cOpp3.LeftPadding = ((uint)(12));
			this.frame10.Add (this.cOpp3);
			this.lblOpp3 = new global::Gtk.Label ();
			this.lblOpp3.Name = "lblOpp3";
			this.lblOpp3.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>3. Opp</i>");
			this.lblOpp3.UseMarkup = true;
			this.frame10.LabelWidget = this.lblOpp3;
			this.ebOpp3.Add (this.frame10);
			this.table.Add (this.ebOpp3);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table [this.ebOpp3]));
			w27.TopAttach = ((uint)(11));
			w27.BottomAttach = ((uint)(12));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table.Gtk.Table+TableChild
			this.ebTeamGov = new global::Gtk.EventBox ();
			this.ebTeamGov.Name = "ebTeamGov";
			// Container child ebTeamGov.Gtk.Container+ContainerChild
			this.frame12 = new global::Gtk.Frame ();
			this.frame12.Name = "frame12";
			this.frame12.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame12.Gtk.Container+ContainerChild
			this.cTeamGov = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.cTeamGov.Name = "cTeamGov";
			this.cTeamGov.LeftPadding = ((uint)(12));
			this.frame12.Add (this.cTeamGov);
			this.GtkLabel11 = new global::Gtk.Label ();
			this.GtkLabel11.Name = "GtkLabel11";
			this.GtkLabel11.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>Gov</i>");
			this.GtkLabel11.UseMarkup = true;
			this.frame12.LabelWidget = this.GtkLabel11;
			this.ebTeamGov.Add (this.frame12);
			this.table.Add (this.ebTeamGov);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table [this.ebTeamGov]));
			w30.TopAttach = ((uint)(16));
			w30.BottomAttach = ((uint)(17));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table.Gtk.Table+TableChild
			this.ebTeamOpp = new global::Gtk.EventBox ();
			this.ebTeamOpp.Name = "ebTeamOpp";
			// Container child ebTeamOpp.Gtk.Container+ContainerChild
			this.frame13 = new global::Gtk.Frame ();
			this.frame13.Name = "frame13";
			this.frame13.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame13.Gtk.Container+ContainerChild
			this.cTeamOpp = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.cTeamOpp.Name = "cTeamOpp";
			this.cTeamOpp.LeftPadding = ((uint)(12));
			this.frame13.Add (this.cTeamOpp);
			this.GtkLabel12 = new global::Gtk.Label ();
			this.GtkLabel12.Name = "GtkLabel12";
			this.GtkLabel12.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>Opp</i>");
			this.GtkLabel12.UseMarkup = true;
			this.frame13.LabelWidget = this.GtkLabel12;
			this.ebTeamOpp.Add (this.frame13);
			this.table.Add (this.ebTeamOpp);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table [this.ebTeamOpp]));
			w33.TopAttach = ((uint)(17));
			w33.BottomAttach = ((uint)(18));
			w33.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Teams</b>");
			this.label4.UseMarkup = true;
			this.table.Add (this.label4);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table [this.label4]));
			w34.TopAttach = ((uint)(14));
			w34.BottomAttach = ((uint)(15));
			w34.YPadding = ((uint)(6));
			w34.XOptions = ((global::Gtk.AttachOptions)(4));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Debater</b>");
			this.label5.UseMarkup = true;
			this.table.Add (this.label5);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table [this.label5]));
			w35.XOptions = ((global::Gtk.AttachOptions)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add (this.table);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table]));
			w36.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.lblNoRoomData = new global::Gtk.Label ();
			this.lblNoRoomData.Name = "lblNoRoomData";
			this.lblNoRoomData.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>No incomplete Rooms found. Please select a Room.</i>");
			this.lblNoRoomData.UseMarkup = true;
			this.vbox1.Add (this.lblNoRoomData);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.lblNoRoomData]));
			w37.Position = 1;
			w37.Expand = false;
			w37.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
