
// This file has been generated by the GUI designer. Do not modify.
namespace OPDtabGui
{
	public partial class EditDebaters
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.HButtonBox hbuttonbox1;
		private global::Gtk.Button btnDebaterAdd;
		private global::Gtk.Button btnDebaterRemove;
		private global::Gtk.Alignment cEntryFilter;
		private global::Gtk.Label lblDebatersInfo;
		private global::Gtk.Button btnExportCSV;
		private global::Gtk.Button btnExportPDF;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeDebaters;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget OPDtabGui.EditDebaters
			this.Name = "OPDtabGui.EditDebaters";
			this.Title = global::Mono.Unix.Catalog.GetString ("EditDebaters");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("OPDtabGui.AppIcon.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Modal = true;
			// Container child OPDtabGui.EditDebaters.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.Name = "hbuttonbox1";
			this.hbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnDebaterAdd = new global::Gtk.Button ();
			this.btnDebaterAdd.CanFocus = true;
			this.btnDebaterAdd.Name = "btnDebaterAdd";
			this.btnDebaterAdd.UseUnderline = true;
			// Container child btnDebaterAdd.Gtk.Container+ContainerChild
			global::Gtk.Alignment w1 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w2 = new global::Gtk.HBox ();
			w2.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w3 = new global::Gtk.Image ();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w2.Add (w3);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w5 = new global::Gtk.Label ();
			w5.LabelProp = global::Mono.Unix.Catalog.GetString ("Add");
			w5.UseUnderline = true;
			w2.Add (w5);
			w1.Add (w2);
			this.btnDebaterAdd.Add (w1);
			this.hbuttonbox1.Add (this.btnDebaterAdd);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.btnDebaterAdd]));
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnDebaterRemove = new global::Gtk.Button ();
			this.btnDebaterRemove.CanFocus = true;
			this.btnDebaterRemove.Name = "btnDebaterRemove";
			this.btnDebaterRemove.UseUnderline = true;
			// Container child btnDebaterRemove.Gtk.Container+ContainerChild
			global::Gtk.Alignment w10 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w11 = new global::Gtk.HBox ();
			w11.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w12 = new global::Gtk.Image ();
			w12.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-remove", global::Gtk.IconSize.Menu);
			w11.Add (w12);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w14 = new global::Gtk.Label ();
			w14.LabelProp = global::Mono.Unix.Catalog.GetString ("Remove");
			w14.UseUnderline = true;
			w11.Add (w14);
			w10.Add (w11);
			this.btnDebaterRemove.Add (w10);
			this.hbuttonbox1.Add (this.btnDebaterRemove);
			global::Gtk.ButtonBox.ButtonBoxChild w18 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.btnDebaterRemove]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.hbox1.Add (this.hbuttonbox1);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbuttonbox1]));
			w19.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.cEntryFilter = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.cEntryFilter.Name = "cEntryFilter";
			this.hbox1.Add (this.cEntryFilter);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cEntryFilter]));
			w20.PackType = ((global::Gtk.PackType)(1));
			w20.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblDebatersInfo = new global::Gtk.Label ();
			this.lblDebatersInfo.Name = "lblDebatersInfo";
			this.lblDebatersInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("lblDebatersInfo");
			this.hbox1.Add (this.lblDebatersInfo);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblDebatersInfo]));
			w21.PackType = ((global::Gtk.PackType)(1));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnExportCSV = new global::Gtk.Button ();
			this.btnExportCSV.CanFocus = true;
			this.btnExportCSV.Name = "btnExportCSV";
			this.btnExportCSV.UseUnderline = true;
			this.btnExportCSV.Label = global::Mono.Unix.Catalog.GetString ("Export as CSV");
			this.hbox1.Add (this.btnExportCSV);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnExportCSV]));
			w22.PackType = ((global::Gtk.PackType)(1));
			w22.Position = 3;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnExportPDF = new global::Gtk.Button ();
			this.btnExportPDF.CanFocus = true;
			this.btnExportPDF.Name = "btnExportPDF";
			this.btnExportPDF.UseUnderline = true;
			this.btnExportPDF.Label = global::Mono.Unix.Catalog.GetString ("Export as PDF");
			this.hbox1.Add (this.btnExportPDF);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnExportPDF]));
			w23.PackType = ((global::Gtk.PackType)(1));
			w23.Position = 4;
			w23.Expand = false;
			w23.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeDebaters = new global::Gtk.TreeView ();
			this.treeDebaters.CanFocus = true;
			this.treeDebaters.Name = "treeDebaters";
			this.treeDebaters.EnableSearch = false;
			this.treeDebaters.RulesHint = true;
			this.GtkScrolledWindow.Add (this.treeDebaters);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w26.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1104;
			this.DefaultHeight = 707;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.btnDebaterAdd.Clicked += new global::System.EventHandler (this.OnBtnDebaterAddClicked);
			this.btnDebaterRemove.Clicked += new global::System.EventHandler (this.OnBtnDebaterRemoveClicked);
			this.btnExportPDF.Clicked += new global::System.EventHandler (this.OnBtnExportPDFClicked);
			this.btnExportCSV.Clicked += new global::System.EventHandler (this.OnBtnExportCSVClicked);
		}
	}
}
