
// This file has been generated by the GUI designer. Do not modify.
namespace OPDtabGui
{
	public partial class MyButton
	{
		private global::Gtk.HBox hbox;
		private global::Gtk.Image image;
		private global::Gtk.Label label;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget OPDtabGui.MyButton
			global::Stetic.BinContainer.Attach (this);
			this.Name = "OPDtabGui.MyButton";
			// Container child OPDtabGui.MyButton.Gtk.Container+ContainerChild
			this.hbox = new global::Gtk.HBox ();
			this.hbox.Name = "hbox";
			this.hbox.Spacing = 3;
			this.hbox.BorderWidth = ((uint)(5));
			// Container child hbox.Gtk.Box+BoxChild
			this.image = new global::Gtk.Image ();
			this.image.Name = "image";
			this.hbox.Add (this.image);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox [this.image]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox.Gtk.Box+BoxChild
			this.label = new global::Gtk.Label ();
			this.label.Name = "label";
			this.label.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.hbox.Add (this.label);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox [this.label]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.Add (this.hbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
